spring:
  application:
    name: state-service

aws:
  dynamodb:
    region: ${AWS_REGION:eu-west-3}
    endpoint: ${DYNAMODB_ENDPOINT:http://localhost:8000}

logging:
  level:
    com.krizaldis: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
